# environment
keyd hyprland hyprpaper hypridle waybar rofi swaync
pavucontrol pipewire pipewire-pulse wireplumber
iw wireless-regdb
wl-clipboard grim slurp


# terminal apps
ghostty zsh neovim yazi


# cli tools
git gcc openssh
man-db man-pages wikiman tealdeer 
fastfetch unzip less wget
fzf ripgrep fd

# fonts
ttf-monofur ttf-jetbrains-mono-nerd


# gui apps
firefox discord steam
code
krita
reaper surge-xt
